services:
  rocland-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rocland-frontend
    ports:
      # El host expone el 4200, pero internamente Nginx escucha en el 80
      - "4200:80"
    restart: always