name: Rocland Frontend CI/CD Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: 1. Descargar el código más reciente
        uses: actions/checkout@v4

      # Opcional pero recomendado: Asegura que el runner use la versión correcta de Node
      - name: 2. Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' 

      - name: 3. Instalar dependencias
        run: npm install

      - name: 4. Compilar Angular para Producción
        run: npm run build --configuration=production